# Generated by Django 4.2.25 on 2025-10-18 17:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(db_index=True, max_length=200)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('movie_year', models.CharField(blank=True, max_length=10, null=True)),
                ('movie_genre', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_poster', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['movie_title'], name='reviews_rev_movie_t_3411df_idx'), models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx')],
            },
        ),
    ]
