# Generated by Django 4.2.25 on 2025-10-23 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_movie_review_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_movie_t_3411df_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_rating_2db6dd_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie_genre',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie_poster',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie_year',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'review')},
        ),
    ]
